// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: service.proto

package service

import (
	_ "github.com/golang/protobuf/ptypes/struct"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Heartbeat request message
type HeartbeatRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Commits    map[string][]byte      `protobuf:"bytes,1,rep,name=commits,proto3" json:"commits,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 提交的CommitSlotItem列表
	Justifieds map[string][]byte      `protobuf:"bytes,2,rep,name=justifieds,proto3" json:"justifieds,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Finalizes  map[string][]byte      `protobuf:"bytes,3,rep,name=finalizes,proto3" json:"finalizes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 完成的CommitSlotItem列表
	Invalids   map[string]int32       `protobuf:"bytes,4,rep,name=invalids,proto3" json:"invalids,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`  // 这个epoch中检测出的有问题的slot
	// map<string, int32> tasks = 3;            // 在这个epoch中过期的任务的最新slot
	Epoch         int32 `protobuf:"varint,5,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatRequest) GetCommits() map[string][]byte {
	if x != nil {
		return x.Commits
	}
	return nil
}

func (x *HeartbeatRequest) GetJustifieds() map[string][]byte {
	if x != nil {
		return x.Justifieds
	}
	return nil
}

func (x *HeartbeatRequest) GetFinalizes() map[string][]byte {
	if x != nil {
		return x.Finalizes
	}
	return nil
}

func (x *HeartbeatRequest) GetInvalids() map[string]int32 {
	if x != nil {
		return x.Invalids
	}
	return nil
}

func (x *HeartbeatRequest) GetEpoch() int32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"` // 节点id
	CpuUsage      int32                  `protobuf:"varint,2,opt,name=cpuUsage,proto3" json:"cpuUsage,omitempty"`
	DiskAvailable int32                  `protobuf:"varint,3,opt,name=diskAvailable,proto3" json:"diskAvailable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatResponse) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *HeartbeatResponse) GetCpuUsage() int32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *HeartbeatResponse) GetDiskAvailable() int32 {
	if x != nil {
		return x.DiskAvailable
	}
	return 0
}

type ScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sign          string                 `protobuf:"bytes,1,opt,name=sign,proto3" json:"sign,omitempty"`   // 任务标记
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`  // 给该节点的任务数量
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"` // 模型名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleRequest) Reset() {
	*x = ScheduleRequest{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleRequest) ProtoMessage() {}

func (x *ScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleRequest.ProtoReflect.Descriptor instead.
func (*ScheduleRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *ScheduleRequest) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *ScheduleRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ScheduleRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type ScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accept        bool                   `protobuf:"varint,1,opt,name=accept,proto3" json:"accept,omitempty"` // 是否接受
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleResponse) Reset() {
	*x = ScheduleResponse{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleResponse) ProtoMessage() {}

func (x *ScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleResponse.ProtoReflect.Descriptor instead.
func (*ScheduleResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *ScheduleResponse) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

type SlotCommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotHash      string                 `protobuf:"bytes,1,opt,name=slotHash,proto3" json:"slotHash,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Commitment    []byte                 `protobuf:"bytes,3,opt,name=commitment,proto3" json:"commitment,omitempty"` // 数据的完整性承诺
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`   // 需要节点对此签名
	Votes         [][]byte               `protobuf:"bytes,5,rep,name=votes,proto3" json:"votes,omitempty"`           // 如果是ec或者多副本，需要其他节点的签名
	Store         int32                  `protobuf:"varint,6,opt,name=store,proto3" json:"store,omitempty"`          // 存储方式,0=ec; 1=local; 2=replicas
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotCommitRequest) Reset() {
	*x = SlotCommitRequest{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotCommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotCommitRequest) ProtoMessage() {}

func (x *SlotCommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotCommitRequest.ProtoReflect.Descriptor instead.
func (*SlotCommitRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *SlotCommitRequest) GetSlotHash() string {
	if x != nil {
		return x.SlotHash
	}
	return ""
}

func (x *SlotCommitRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SlotCommitRequest) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

func (x *SlotCommitRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SlotCommitRequest) GetVotes() [][]byte {
	if x != nil {
		return x.Votes
	}
	return nil
}

func (x *SlotCommitRequest) GetStore() int32 {
	if x != nil {
		return x.Store
	}
	return 0
}

type SlotCommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accept        bool                   `protobuf:"varint,1,opt,name=accept,proto3" json:"accept,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotCommitResponse) Reset() {
	*x = SlotCommitResponse{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotCommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotCommitResponse) ProtoMessage() {}

func (x *SlotCommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotCommitResponse.ProtoReflect.Descriptor instead.
func (*SlotCommitResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *SlotCommitResponse) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

type RecoverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mission       string                 `protobuf:"bytes,1,opt,name=mission,proto3" json:"mission,omitempty"`
	Hashs         []string               `protobuf:"bytes,2,rep,name=hashs,proto3" json:"hashs,omitempty"` // 所有要收集的slotHash
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecoverRequest) Reset() {
	*x = RecoverRequest{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverRequest) ProtoMessage() {}

func (x *RecoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverRequest.ProtoReflect.Descriptor instead.
func (*RecoverRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *RecoverRequest) GetMission() string {
	if x != nil {
		return x.Mission
	}
	return ""
}

func (x *RecoverRequest) GetHashs() []string {
	if x != nil {
		return x.Hashs
	}
	return nil
}

// 每个chunk，这里是行块的ec块
type RecoverSlotChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`   // slot hash
	Row           int32                  `protobuf:"varint,2,opt,name=row,proto3" json:"row,omitempty"`    // 行块对应的index
	Col           int32                  `protobuf:"varint,3,opt,name=col,proto3" json:"col,omitempty"`    // ec的index
	Chunk         []byte                 `protobuf:"bytes,4,opt,name=chunk,proto3" json:"chunk,omitempty"` // chunk的内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecoverSlotChunk) Reset() {
	*x = RecoverSlotChunk{}
	mi := &file_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoverSlotChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverSlotChunk) ProtoMessage() {}

func (x *RecoverSlotChunk) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverSlotChunk.ProtoReflect.Descriptor instead.
func (*RecoverSlotChunk) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *RecoverSlotChunk) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *RecoverSlotChunk) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *RecoverSlotChunk) GetCol() int32 {
	if x != nil {
		return x.Col
	}
	return 0
}

func (x *RecoverSlotChunk) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type RecoverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        []*RecoverSlotChunk    `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"` // 本地的对应的chunks
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecoverResponse) Reset() {
	*x = RecoverResponse{}
	mi := &file_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverResponse) ProtoMessage() {}

func (x *RecoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverResponse.ProtoReflect.Descriptor instead.
func (*RecoverResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{8}
}

func (x *RecoverResponse) GetChunks() []*RecoverSlotChunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\aservice\x1a\x1cgoogle/protobuf/struct.proto\"\xb8\x04\n" +
	"\x10HeartbeatRequest\x12@\n" +
	"\acommits\x18\x01 \x03(\v2&.service.HeartbeatRequest.CommitsEntryR\acommits\x12I\n" +
	"\n" +
	"justifieds\x18\x02 \x03(\v2).service.HeartbeatRequest.JustifiedsEntryR\n" +
	"justifieds\x12F\n" +
	"\tfinalizes\x18\x03 \x03(\v2(.service.HeartbeatRequest.FinalizesEntryR\tfinalizes\x12C\n" +
	"\binvalids\x18\x04 \x03(\v2'.service.HeartbeatRequest.InvalidsEntryR\binvalids\x12\x14\n" +
	"\x05epoch\x18\x05 \x01(\x05R\x05epoch\x1a:\n" +
	"\fCommitsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a=\n" +
	"\x0fJustifiedsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a<\n" +
	"\x0eFinalizesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a;\n" +
	"\rInvalidsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"m\n" +
	"\x11HeartbeatResponse\x12\x16\n" +
	"\x06nodeId\x18\x01 \x01(\x05R\x06nodeId\x12\x1a\n" +
	"\bcpuUsage\x18\x02 \x01(\x05R\bcpuUsage\x12$\n" +
	"\rdiskAvailable\x18\x03 \x01(\x05R\rdiskAvailable\"O\n" +
	"\x0fScheduleRequest\x12\x12\n" +
	"\x04sign\x18\x01 \x01(\tR\x04sign\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\"*\n" +
	"\x10ScheduleResponse\x12\x16\n" +
	"\x06accept\x18\x01 \x01(\bR\x06accept\"\xad\x01\n" +
	"\x11SlotCommitRequest\x12\x1a\n" +
	"\bslotHash\x18\x01 \x01(\tR\bslotHash\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x1e\n" +
	"\n" +
	"commitment\x18\x03 \x01(\fR\n" +
	"commitment\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\x12\x14\n" +
	"\x05votes\x18\x05 \x03(\fR\x05votes\x12\x14\n" +
	"\x05store\x18\x06 \x01(\x05R\x05store\",\n" +
	"\x12SlotCommitResponse\x12\x16\n" +
	"\x06accept\x18\x01 \x01(\bR\x06accept\"@\n" +
	"\x0eRecoverRequest\x12\x18\n" +
	"\amission\x18\x01 \x01(\tR\amission\x12\x14\n" +
	"\x05hashs\x18\x02 \x03(\tR\x05hashs\"`\n" +
	"\x10RecoverSlotChunk\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x10\n" +
	"\x03row\x18\x02 \x01(\x05R\x03row\x12\x10\n" +
	"\x03col\x18\x03 \x01(\x05R\x03col\x12\x14\n" +
	"\x05chunk\x18\x04 \x01(\fR\x05chunk\"D\n" +
	"\x0fRecoverResponse\x121\n" +
	"\x06chunks\x18\x01 \x03(\v2\x19.service.RecoverSlotChunkR\x06chunks2T\n" +
	"\vRappaMaster\x12E\n" +
	"\n" +
	"CommitSlot\x12\x1a.service.SlotCommitRequest\x1a\x1b.service.SlotCommitResponse2\xd5\x01\n" +
	"\x10RappaSynthesizer\x12B\n" +
	"\tHeartbeat\x12\x19.service.HeartbeatRequest\x1a\x1a.service.HeartbeatResponse\x12?\n" +
	"\bSchedule\x12\x18.service.ScheduleRequest\x1a\x19.service.ScheduleResponse\x12<\n" +
	"\aCollect\x12\x17.service.RecoverRequest\x1a\x18.service.RecoverResponseB\n" +
	"Z\b/serviceb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_service_proto_goTypes = []any{
	(*HeartbeatRequest)(nil),   // 0: service.HeartbeatRequest
	(*HeartbeatResponse)(nil),  // 1: service.HeartbeatResponse
	(*ScheduleRequest)(nil),    // 2: service.ScheduleRequest
	(*ScheduleResponse)(nil),   // 3: service.ScheduleResponse
	(*SlotCommitRequest)(nil),  // 4: service.SlotCommitRequest
	(*SlotCommitResponse)(nil), // 5: service.SlotCommitResponse
	(*RecoverRequest)(nil),     // 6: service.RecoverRequest
	(*RecoverSlotChunk)(nil),   // 7: service.RecoverSlotChunk
	(*RecoverResponse)(nil),    // 8: service.RecoverResponse
	nil,                        // 9: service.HeartbeatRequest.CommitsEntry
	nil,                        // 10: service.HeartbeatRequest.JustifiedsEntry
	nil,                        // 11: service.HeartbeatRequest.FinalizesEntry
	nil,                        // 12: service.HeartbeatRequest.InvalidsEntry
}
var file_service_proto_depIdxs = []int32{
	9,  // 0: service.HeartbeatRequest.commits:type_name -> service.HeartbeatRequest.CommitsEntry
	10, // 1: service.HeartbeatRequest.justifieds:type_name -> service.HeartbeatRequest.JustifiedsEntry
	11, // 2: service.HeartbeatRequest.finalizes:type_name -> service.HeartbeatRequest.FinalizesEntry
	12, // 3: service.HeartbeatRequest.invalids:type_name -> service.HeartbeatRequest.InvalidsEntry
	7,  // 4: service.RecoverResponse.chunks:type_name -> service.RecoverSlotChunk
	4,  // 5: service.RappaMaster.CommitSlot:input_type -> service.SlotCommitRequest
	0,  // 6: service.RappaSynthesizer.Heartbeat:input_type -> service.HeartbeatRequest
	2,  // 7: service.RappaSynthesizer.Schedule:input_type -> service.ScheduleRequest
	6,  // 8: service.RappaSynthesizer.Collect:input_type -> service.RecoverRequest
	5,  // 9: service.RappaMaster.CommitSlot:output_type -> service.SlotCommitResponse
	1,  // 10: service.RappaSynthesizer.Heartbeat:output_type -> service.HeartbeatResponse
	3,  // 11: service.RappaSynthesizer.Schedule:output_type -> service.ScheduleResponse
	8,  // 12: service.RappaSynthesizer.Collect:output_type -> service.RecoverResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
