// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.6.1
// source: service.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RappaMaster_CommitSlot_FullMethodName = "/service.RappaMaster/CommitSlot"
)

// RappaMasterClient is the client API for RappaMaster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// **
// NOTE: 定义Master处的接口
// *
type RappaMasterClient interface {
	// CommitSlot Executor向Master提交自己完成的Task Slot
	CommitSlot(ctx context.Context, in *SlotCommitRequest, opts ...grpc.CallOption) (*SlotCommitResponse, error)
}

type rappaMasterClient struct {
	cc grpc.ClientConnInterface
}

func NewRappaMasterClient(cc grpc.ClientConnInterface) RappaMasterClient {
	return &rappaMasterClient{cc}
}

func (c *rappaMasterClient) CommitSlot(ctx context.Context, in *SlotCommitRequest, opts ...grpc.CallOption) (*SlotCommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SlotCommitResponse)
	err := c.cc.Invoke(ctx, RappaMaster_CommitSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RappaMasterServer is the server API for RappaMaster service.
// All implementations must embed UnimplementedRappaMasterServer
// for forward compatibility.
//
// **
// NOTE: 定义Master处的接口
// *
type RappaMasterServer interface {
	// CommitSlot Executor向Master提交自己完成的Task Slot
	CommitSlot(context.Context, *SlotCommitRequest) (*SlotCommitResponse, error)
	mustEmbedUnimplementedRappaMasterServer()
}

// UnimplementedRappaMasterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRappaMasterServer struct{}

func (UnimplementedRappaMasterServer) CommitSlot(context.Context, *SlotCommitRequest) (*SlotCommitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitSlot not implemented")
}
func (UnimplementedRappaMasterServer) mustEmbedUnimplementedRappaMasterServer() {}
func (UnimplementedRappaMasterServer) testEmbeddedByValue()                     {}

// UnsafeRappaMasterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RappaMasterServer will
// result in compilation errors.
type UnsafeRappaMasterServer interface {
	mustEmbedUnimplementedRappaMasterServer()
}

func RegisterRappaMasterServer(s grpc.ServiceRegistrar, srv RappaMasterServer) {
	// If the following call pancis, it indicates UnimplementedRappaMasterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RappaMaster_ServiceDesc, srv)
}

func _RappaMaster_CommitSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlotCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RappaMasterServer).CommitSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RappaMaster_CommitSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RappaMasterServer).CommitSlot(ctx, req.(*SlotCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RappaMaster_ServiceDesc is the grpc.ServiceDesc for RappaMaster service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RappaMaster_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.RappaMaster",
	HandlerType: (*RappaMasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CommitSlot",
			Handler:    _RappaMaster_CommitSlot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

const (
	RappaExecutor_Heartbeat_FullMethodName = "/service.RappaExecutor/Heartbeat"
	RappaExecutor_Schedule_FullMethodName  = "/service.RappaExecutor/Schedule"
	RappaExecutor_Collect_FullMethodName   = "/service.RappaExecutor/Collect"
)

// RappaExecutorClient is the client API for RappaExecutor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// **
// NOTE: 定义Executor处的接口
// *
type RappaExecutorClient interface {
	// Heartbeat 向follower同步slot状态，同时监控节点状态
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// Schedule 用于向节点发送调度
	Schedule(ctx context.Context, in *ScheduleRequest, opts ...grpc.CallOption) (*ScheduleResponse, error)
	// Collect 用于向节点收集chunk，恢复文件数据
	Collect(ctx context.Context, in *RecoverRequest, opts ...grpc.CallOption) (*RecoverResponse, error)
}

type rappaExecutorClient struct {
	cc grpc.ClientConnInterface
}

func NewRappaExecutorClient(cc grpc.ClientConnInterface) RappaExecutorClient {
	return &rappaExecutorClient{cc}
}

func (c *rappaExecutorClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, RappaExecutor_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rappaExecutorClient) Schedule(ctx context.Context, in *ScheduleRequest, opts ...grpc.CallOption) (*ScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleResponse)
	err := c.cc.Invoke(ctx, RappaExecutor_Schedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rappaExecutorClient) Collect(ctx context.Context, in *RecoverRequest, opts ...grpc.CallOption) (*RecoverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecoverResponse)
	err := c.cc.Invoke(ctx, RappaExecutor_Collect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RappaExecutorServer is the server API for RappaExecutor service.
// All implementations must embed UnimplementedRappaExecutorServer
// for forward compatibility.
//
// **
// NOTE: 定义Executor处的接口
// *
type RappaExecutorServer interface {
	// Heartbeat 向follower同步slot状态，同时监控节点状态
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// Schedule 用于向节点发送调度
	Schedule(context.Context, *ScheduleRequest) (*ScheduleResponse, error)
	// Collect 用于向节点收集chunk，恢复文件数据
	Collect(context.Context, *RecoverRequest) (*RecoverResponse, error)
	mustEmbedUnimplementedRappaExecutorServer()
}

// UnimplementedRappaExecutorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRappaExecutorServer struct{}

func (UnimplementedRappaExecutorServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedRappaExecutorServer) Schedule(context.Context, *ScheduleRequest) (*ScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Schedule not implemented")
}
func (UnimplementedRappaExecutorServer) Collect(context.Context, *RecoverRequest) (*RecoverResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Collect not implemented")
}
func (UnimplementedRappaExecutorServer) mustEmbedUnimplementedRappaExecutorServer() {}
func (UnimplementedRappaExecutorServer) testEmbeddedByValue()                       {}

// UnsafeRappaExecutorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RappaExecutorServer will
// result in compilation errors.
type UnsafeRappaExecutorServer interface {
	mustEmbedUnimplementedRappaExecutorServer()
}

func RegisterRappaExecutorServer(s grpc.ServiceRegistrar, srv RappaExecutorServer) {
	// If the following call pancis, it indicates UnimplementedRappaExecutorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RappaExecutor_ServiceDesc, srv)
}

func _RappaExecutor_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RappaExecutorServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RappaExecutor_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RappaExecutorServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RappaExecutor_Schedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RappaExecutorServer).Schedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RappaExecutor_Schedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RappaExecutorServer).Schedule(ctx, req.(*ScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RappaExecutor_Collect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RappaExecutorServer).Collect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RappaExecutor_Collect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RappaExecutorServer).Collect(ctx, req.(*RecoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RappaExecutor_ServiceDesc is the grpc.ServiceDesc for RappaExecutor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RappaExecutor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.RappaExecutor",
	HandlerType: (*RappaExecutorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _RappaExecutor_Heartbeat_Handler,
		},
		{
			MethodName: "Schedule",
			Handler:    _RappaExecutor_Schedule_Handler,
		},
		{
			MethodName: "Collect",
			Handler:    _RappaExecutor_Collect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
