// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.6.1
// source: service.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RappaMaster_CommitSlot_FullMethodName = "/service.RappaMaster/CommitSlot"
)

// RappaMasterClient is the client API for RappaMaster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RappaMasterClient interface {
	CommitSlot(ctx context.Context, in *SlotCommitRequest, opts ...grpc.CallOption) (*SlotCommitResponse, error)
}

type rappaMasterClient struct {
	cc grpc.ClientConnInterface
}

func NewRappaMasterClient(cc grpc.ClientConnInterface) RappaMasterClient {
	return &rappaMasterClient{cc}
}

func (c *rappaMasterClient) CommitSlot(ctx context.Context, in *SlotCommitRequest, opts ...grpc.CallOption) (*SlotCommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SlotCommitResponse)
	err := c.cc.Invoke(ctx, RappaMaster_CommitSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RappaMasterServer is the server API for RappaMaster service.
// All implementations must embed UnimplementedRappaMasterServer
// for forward compatibility.
type RappaMasterServer interface {
	CommitSlot(context.Context, *SlotCommitRequest) (*SlotCommitResponse, error)
	mustEmbedUnimplementedRappaMasterServer()
}

// UnimplementedRappaMasterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRappaMasterServer struct{}

func (UnimplementedRappaMasterServer) CommitSlot(context.Context, *SlotCommitRequest) (*SlotCommitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitSlot not implemented")
}
func (UnimplementedRappaMasterServer) mustEmbedUnimplementedRappaMasterServer() {}
func (UnimplementedRappaMasterServer) testEmbeddedByValue()                     {}

// UnsafeRappaMasterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RappaMasterServer will
// result in compilation errors.
type UnsafeRappaMasterServer interface {
	mustEmbedUnimplementedRappaMasterServer()
}

func RegisterRappaMasterServer(s grpc.ServiceRegistrar, srv RappaMasterServer) {
	// If the following call pancis, it indicates UnimplementedRappaMasterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RappaMaster_ServiceDesc, srv)
}

func _RappaMaster_CommitSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlotCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RappaMasterServer).CommitSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RappaMaster_CommitSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RappaMasterServer).CommitSlot(ctx, req.(*SlotCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RappaMaster_ServiceDesc is the grpc.ServiceDesc for RappaMaster service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RappaMaster_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.RappaMaster",
	HandlerType: (*RappaMasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CommitSlot",
			Handler:    _RappaMaster_CommitSlot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

const (
	RappaSynthesizer_Heartbeat_FullMethodName = "/service.RappaSynthesizer/Heartbeat"
	RappaSynthesizer_Schedule_FullMethodName  = "/service.RappaSynthesizer/Schedule"
)

// RappaSynthesizerClient is the client API for RappaSynthesizer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RappaSynthesizerClient interface {
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	Schedule(ctx context.Context, in *ScheduleRequest, opts ...grpc.CallOption) (*ScheduleResponse, error)
}

type rappaSynthesizerClient struct {
	cc grpc.ClientConnInterface
}

func NewRappaSynthesizerClient(cc grpc.ClientConnInterface) RappaSynthesizerClient {
	return &rappaSynthesizerClient{cc}
}

func (c *rappaSynthesizerClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, RappaSynthesizer_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rappaSynthesizerClient) Schedule(ctx context.Context, in *ScheduleRequest, opts ...grpc.CallOption) (*ScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleResponse)
	err := c.cc.Invoke(ctx, RappaSynthesizer_Schedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RappaSynthesizerServer is the server API for RappaSynthesizer service.
// All implementations must embed UnimplementedRappaSynthesizerServer
// for forward compatibility.
type RappaSynthesizerServer interface {
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	Schedule(context.Context, *ScheduleRequest) (*ScheduleResponse, error)
	mustEmbedUnimplementedRappaSynthesizerServer()
}

// UnimplementedRappaSynthesizerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRappaSynthesizerServer struct{}

func (UnimplementedRappaSynthesizerServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedRappaSynthesizerServer) Schedule(context.Context, *ScheduleRequest) (*ScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Schedule not implemented")
}
func (UnimplementedRappaSynthesizerServer) mustEmbedUnimplementedRappaSynthesizerServer() {}
func (UnimplementedRappaSynthesizerServer) testEmbeddedByValue()                          {}

// UnsafeRappaSynthesizerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RappaSynthesizerServer will
// result in compilation errors.
type UnsafeRappaSynthesizerServer interface {
	mustEmbedUnimplementedRappaSynthesizerServer()
}

func RegisterRappaSynthesizerServer(s grpc.ServiceRegistrar, srv RappaSynthesizerServer) {
	// If the following call pancis, it indicates UnimplementedRappaSynthesizerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RappaSynthesizer_ServiceDesc, srv)
}

func _RappaSynthesizer_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RappaSynthesizerServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RappaSynthesizer_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RappaSynthesizerServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RappaSynthesizer_Schedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RappaSynthesizerServer).Schedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RappaSynthesizer_Schedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RappaSynthesizerServer).Schedule(ctx, req.(*ScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RappaSynthesizer_ServiceDesc is the grpc.ServiceDesc for RappaSynthesizer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RappaSynthesizer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.RappaSynthesizer",
	HandlerType: (*RappaSynthesizerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _RappaSynthesizer_Heartbeat_Handler,
		},
		{
			MethodName: "Schedule",
			Handler:    _RappaSynthesizer_Schedule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
