// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: service.proto

package service

import (
	_ "github.com/golang/protobuf/ptypes/struct"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Heartbeat request message - master sends to nodes
type HeartbeatRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Commits    map[string][]byte      `protobuf:"bytes,1,rep,name=commits,proto3" json:"commits,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 提交的CommitSlotItem列表
	Justifieds map[string][]byte      `protobuf:"bytes,2,rep,name=justifieds,proto3" json:"justifieds,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Finalizes  map[string][]byte      `protobuf:"bytes,3,rep,name=finalizes,proto3" json:"finalizes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 完成的CommitSlotItem列表
	Invalids   map[string]int32       `protobuf:"bytes,4,rep,name=invalids,proto3" json:"invalids,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`  // 这个epoch中检测出的有问题的slot
	Epoch      int32                  `protobuf:"varint,5,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// New fields for epoch validation
	EpochRoot       string            `protobuf:"bytes,6,opt,name=epochRoot,proto3" json:"epochRoot,omitempty"`             // Epoch merkle root
	NodeMerkleInfos []*NodeMerkleInfo `protobuf:"bytes,7,rep,name=nodeMerkleInfos,proto3" json:"nodeMerkleInfos,omitempty"` // Merkle info for each node
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatRequest) GetCommits() map[string][]byte {
	if x != nil {
		return x.Commits
	}
	return nil
}

func (x *HeartbeatRequest) GetJustifieds() map[string][]byte {
	if x != nil {
		return x.Justifieds
	}
	return nil
}

func (x *HeartbeatRequest) GetFinalizes() map[string][]byte {
	if x != nil {
		return x.Finalizes
	}
	return nil
}

func (x *HeartbeatRequest) GetInvalids() map[string]int32 {
	if x != nil {
		return x.Invalids
	}
	return nil
}

func (x *HeartbeatRequest) GetEpoch() int32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *HeartbeatRequest) GetEpochRoot() string {
	if x != nil {
		return x.EpochRoot
	}
	return ""
}

func (x *HeartbeatRequest) GetNodeMerkleInfos() []*NodeMerkleInfo {
	if x != nil {
		return x.NodeMerkleInfos
	}
	return nil
}

// Merkle information sent to each node
type NodeMerkleInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeId           int32                  `protobuf:"varint,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	NodeRoot         string                 `protobuf:"bytes,2,opt,name=nodeRoot,proto3" json:"nodeRoot,omitempty"`                 // Merkle root of slots for this node
	TaskProofs       []*TaskMerkleProof     `protobuf:"bytes,3,rep,name=taskProofs,proto3" json:"taskProofs,omitempty"`             // Task merkle proofs
	EpochMerkleProof string                 `protobuf:"bytes,4,opt,name=epochMerkleProof,proto3" json:"epochMerkleProof,omitempty"` // Proof of epochRoot
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NodeMerkleInfo) Reset() {
	*x = NodeMerkleInfo{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMerkleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMerkleInfo) ProtoMessage() {}

func (x *NodeMerkleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMerkleInfo.ProtoReflect.Descriptor instead.
func (*NodeMerkleInfo) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *NodeMerkleInfo) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *NodeMerkleInfo) GetNodeRoot() string {
	if x != nil {
		return x.NodeRoot
	}
	return ""
}

func (x *NodeMerkleInfo) GetTaskProofs() []*TaskMerkleProof {
	if x != nil {
		return x.TaskProofs
	}
	return nil
}

func (x *NodeMerkleInfo) GetEpochMerkleProof() string {
	if x != nil {
		return x.EpochMerkleProof
	}
	return ""
}

// Task merkle proof information
type TaskMerkleProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskSign      string                 `protobuf:"bytes,1,opt,name=taskSign,proto3" json:"taskSign,omitempty"`
	TaskRoot      string                 `protobuf:"bytes,2,opt,name=taskRoot,proto3" json:"taskRoot,omitempty"`
	MerkleProof   string                 `protobuf:"bytes,3,opt,name=merkleProof,proto3" json:"merkleProof,omitempty"` // JSON encoded merkle proof
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskMerkleProof) Reset() {
	*x = TaskMerkleProof{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskMerkleProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskMerkleProof) ProtoMessage() {}

func (x *TaskMerkleProof) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskMerkleProof.ProtoReflect.Descriptor instead.
func (*TaskMerkleProof) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *TaskMerkleProof) GetTaskSign() string {
	if x != nil {
		return x.TaskSign
	}
	return ""
}

func (x *TaskMerkleProof) GetTaskRoot() string {
	if x != nil {
		return x.TaskRoot
	}
	return ""
}

func (x *TaskMerkleProof) GetMerkleProof() string {
	if x != nil {
		return x.MerkleProof
	}
	return ""
}

// Heartbeat response - nodes send back to master
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"` // 节点id
	CpuUsage      int32                  `protobuf:"varint,2,opt,name=cpuUsage,proto3" json:"cpuUsage,omitempty"`
	DiskAvailable int32                  `protobuf:"varint,3,opt,name=diskAvailable,proto3" json:"diskAvailable,omitempty"`
	// New fields for epoch validation
	EpochSignature  string `protobuf:"bytes,4,opt,name=epochSignature,proto3" json:"epochSignature,omitempty"`   // BLS signature of epochRoot
	EpochValidated  bool   `protobuf:"varint,5,opt,name=epochValidated,proto3" json:"epochValidated,omitempty"`  // Whether node validated the epoch
	ValidationError string `protobuf:"bytes,6,opt,name=validationError,proto3" json:"validationError,omitempty"` // Error message if validation failed
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *HeartbeatResponse) GetCpuUsage() int32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *HeartbeatResponse) GetDiskAvailable() int32 {
	if x != nil {
		return x.DiskAvailable
	}
	return 0
}

func (x *HeartbeatResponse) GetEpochSignature() string {
	if x != nil {
		return x.EpochSignature
	}
	return ""
}

func (x *HeartbeatResponse) GetEpochValidated() bool {
	if x != nil {
		return x.EpochValidated
	}
	return false
}

func (x *HeartbeatResponse) GetValidationError() string {
	if x != nil {
		return x.ValidationError
	}
	return ""
}

type ScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sign          string                 `protobuf:"bytes,1,opt,name=sign,proto3" json:"sign,omitempty"`   // 任务标记
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`  // 给该节点的任务数量
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"` // 模型名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleRequest) Reset() {
	*x = ScheduleRequest{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleRequest) ProtoMessage() {}

func (x *ScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleRequest.ProtoReflect.Descriptor instead.
func (*ScheduleRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *ScheduleRequest) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *ScheduleRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ScheduleRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type ScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accept        bool                   `protobuf:"varint,1,opt,name=accept,proto3" json:"accept,omitempty"` // 是否接受
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleResponse) Reset() {
	*x = ScheduleResponse{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleResponse) ProtoMessage() {}

func (x *ScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleResponse.ProtoReflect.Descriptor instead.
func (*ScheduleResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *ScheduleResponse) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

type SlotCommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotHash      string                 `protobuf:"bytes,1,opt,name=slotHash,proto3" json:"slotHash,omitempty"`
	Sign          string                 `protobuf:"bytes,2,opt,name=sign,proto3" json:"sign,omitempty"`
	NodeID        int32                  `protobuf:"varint,3,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	Size          int32                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Commitment    []byte                 `protobuf:"bytes,5,opt,name=commitment,proto3" json:"commitment,omitempty"` // 数据的完整性承诺
	Signature     []byte                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`   // 需要节点对此签名
	Votes         [][]byte               `protobuf:"bytes,7,rep,name=votes,proto3" json:"votes,omitempty"`           // 如果是ec或者多副本，需要其他节点的签名
	Store         int32                  `protobuf:"varint,8,opt,name=store,proto3" json:"store,omitempty"`          // 存储方式,0=ec; 1=local; 2=replicas
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotCommitRequest) Reset() {
	*x = SlotCommitRequest{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotCommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotCommitRequest) ProtoMessage() {}

func (x *SlotCommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotCommitRequest.ProtoReflect.Descriptor instead.
func (*SlotCommitRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *SlotCommitRequest) GetSlotHash() string {
	if x != nil {
		return x.SlotHash
	}
	return ""
}

func (x *SlotCommitRequest) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *SlotCommitRequest) GetNodeID() int32 {
	if x != nil {
		return x.NodeID
	}
	return 0
}

func (x *SlotCommitRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SlotCommitRequest) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

func (x *SlotCommitRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SlotCommitRequest) GetVotes() [][]byte {
	if x != nil {
		return x.Votes
	}
	return nil
}

func (x *SlotCommitRequest) GetStore() int32 {
	if x != nil {
		return x.Store
	}
	return 0
}

type SlotCommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accept        bool                   `protobuf:"varint,1,opt,name=accept,proto3" json:"accept,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotCommitResponse) Reset() {
	*x = SlotCommitResponse{}
	mi := &file_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotCommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotCommitResponse) ProtoMessage() {}

func (x *SlotCommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotCommitResponse.ProtoReflect.Descriptor instead.
func (*SlotCommitResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *SlotCommitResponse) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\aservice\x1a\x1cgoogle/protobuf/struct.proto\"\x99\x05\n" +
	"\x10HeartbeatRequest\x12@\n" +
	"\acommits\x18\x01 \x03(\v2&.service.HeartbeatRequest.CommitsEntryR\acommits\x12I\n" +
	"\n" +
	"justifieds\x18\x02 \x03(\v2).service.HeartbeatRequest.JustifiedsEntryR\n" +
	"justifieds\x12F\n" +
	"\tfinalizes\x18\x03 \x03(\v2(.service.HeartbeatRequest.FinalizesEntryR\tfinalizes\x12C\n" +
	"\binvalids\x18\x04 \x03(\v2'.service.HeartbeatRequest.InvalidsEntryR\binvalids\x12\x14\n" +
	"\x05epoch\x18\x05 \x01(\x05R\x05epoch\x12\x1c\n" +
	"\tepochRoot\x18\x06 \x01(\tR\tepochRoot\x12A\n" +
	"\x0fnodeMerkleInfos\x18\a \x03(\v2\x17.service.NodeMerkleInfoR\x0fnodeMerkleInfos\x1a:\n" +
	"\fCommitsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a=\n" +
	"\x0fJustifiedsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a<\n" +
	"\x0eFinalizesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a;\n" +
	"\rInvalidsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xaa\x01\n" +
	"\x0eNodeMerkleInfo\x12\x16\n" +
	"\x06nodeId\x18\x01 \x01(\x05R\x06nodeId\x12\x1a\n" +
	"\bnodeRoot\x18\x02 \x01(\tR\bnodeRoot\x128\n" +
	"\n" +
	"taskProofs\x18\x03 \x03(\v2\x18.service.TaskMerkleProofR\n" +
	"taskProofs\x12*\n" +
	"\x10epochMerkleProof\x18\x04 \x01(\tR\x10epochMerkleProof\"k\n" +
	"\x0fTaskMerkleProof\x12\x1a\n" +
	"\btaskSign\x18\x01 \x01(\tR\btaskSign\x12\x1a\n" +
	"\btaskRoot\x18\x02 \x01(\tR\btaskRoot\x12 \n" +
	"\vmerkleProof\x18\x03 \x01(\tR\vmerkleProof\"\xe7\x01\n" +
	"\x11HeartbeatResponse\x12\x16\n" +
	"\x06nodeId\x18\x01 \x01(\x05R\x06nodeId\x12\x1a\n" +
	"\bcpuUsage\x18\x02 \x01(\x05R\bcpuUsage\x12$\n" +
	"\rdiskAvailable\x18\x03 \x01(\x05R\rdiskAvailable\x12&\n" +
	"\x0eepochSignature\x18\x04 \x01(\tR\x0eepochSignature\x12&\n" +
	"\x0eepochValidated\x18\x05 \x01(\bR\x0eepochValidated\x12(\n" +
	"\x0fvalidationError\x18\x06 \x01(\tR\x0fvalidationError\"O\n" +
	"\x0fScheduleRequest\x12\x12\n" +
	"\x04sign\x18\x01 \x01(\tR\x04sign\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\"*\n" +
	"\x10ScheduleResponse\x12\x16\n" +
	"\x06accept\x18\x01 \x01(\bR\x06accept\"\xd9\x01\n" +
	"\x11SlotCommitRequest\x12\x1a\n" +
	"\bslotHash\x18\x01 \x01(\tR\bslotHash\x12\x12\n" +
	"\x04sign\x18\x02 \x01(\tR\x04sign\x12\x16\n" +
	"\x06nodeID\x18\x03 \x01(\x05R\x06nodeID\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x05R\x04size\x12\x1e\n" +
	"\n" +
	"commitment\x18\x05 \x01(\fR\n" +
	"commitment\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature\x12\x14\n" +
	"\x05votes\x18\a \x03(\fR\x05votes\x12\x14\n" +
	"\x05store\x18\b \x01(\x05R\x05store\",\n" +
	"\x12SlotCommitResponse\x12\x16\n" +
	"\x06accept\x18\x01 \x01(\bR\x06accept2T\n" +
	"\vRappaMaster\x12E\n" +
	"\n" +
	"CommitSlot\x12\x1a.service.SlotCommitRequest\x1a\x1b.service.SlotCommitResponse2\x97\x01\n" +
	"\x10RappaSynthesizer\x12B\n" +
	"\tHeartbeat\x12\x19.service.HeartbeatRequest\x1a\x1a.service.HeartbeatResponse\x12?\n" +
	"\bSchedule\x12\x18.service.ScheduleRequest\x1a\x19.service.ScheduleResponseB\n" +
	"Z\b/serviceb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_service_proto_goTypes = []any{
	(*HeartbeatRequest)(nil),   // 0: service.HeartbeatRequest
	(*NodeMerkleInfo)(nil),     // 1: service.NodeMerkleInfo
	(*TaskMerkleProof)(nil),    // 2: service.TaskMerkleProof
	(*HeartbeatResponse)(nil),  // 3: service.HeartbeatResponse
	(*ScheduleRequest)(nil),    // 4: service.ScheduleRequest
	(*ScheduleResponse)(nil),   // 5: service.ScheduleResponse
	(*SlotCommitRequest)(nil),  // 6: service.SlotCommitRequest
	(*SlotCommitResponse)(nil), // 7: service.SlotCommitResponse
	nil,                        // 8: service.HeartbeatRequest.CommitsEntry
	nil,                        // 9: service.HeartbeatRequest.JustifiedsEntry
	nil,                        // 10: service.HeartbeatRequest.FinalizesEntry
	nil,                        // 11: service.HeartbeatRequest.InvalidsEntry
}
var file_service_proto_depIdxs = []int32{
	8,  // 0: service.HeartbeatRequest.commits:type_name -> service.HeartbeatRequest.CommitsEntry
	9,  // 1: service.HeartbeatRequest.justifieds:type_name -> service.HeartbeatRequest.JustifiedsEntry
	10, // 2: service.HeartbeatRequest.finalizes:type_name -> service.HeartbeatRequest.FinalizesEntry
	11, // 3: service.HeartbeatRequest.invalids:type_name -> service.HeartbeatRequest.InvalidsEntry
	1,  // 4: service.HeartbeatRequest.nodeMerkleInfos:type_name -> service.NodeMerkleInfo
	2,  // 5: service.NodeMerkleInfo.taskProofs:type_name -> service.TaskMerkleProof
	6,  // 6: service.RappaMaster.CommitSlot:input_type -> service.SlotCommitRequest
	0,  // 7: service.RappaSynthesizer.Heartbeat:input_type -> service.HeartbeatRequest
	4,  // 8: service.RappaSynthesizer.Schedule:input_type -> service.ScheduleRequest
	7,  // 9: service.RappaMaster.CommitSlot:output_type -> service.SlotCommitResponse
	3,  // 10: service.RappaSynthesizer.Heartbeat:output_type -> service.HeartbeatResponse
	5,  // 11: service.RappaSynthesizer.Schedule:output_type -> service.ScheduleResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
